# Generated by Django 4.1 on 2022-09-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('cost', models.IntegerField(default=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='coin_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='inventory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
