# Generated by Django 4.1 on 2022-09-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0002_beverage_delete_drink_vendingmachine_coin_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='inventory',
            field=models.CharField(default=['SodaSodaSodaSodaSoda', 'WaterWaterWaterWaterWater', 'JuiceJuiceJuiceJuiceJuice'], max_length=500),
        ),
    ]
