# Generated by Django 4.1 on 2022-09-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0003_alter_vendingmachine_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendomatic.beverage'),
        ),
    ]
