# Generated by Django 4.1 on 2022-09-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0004_alter_beverage_type_alter_vendingmachine_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='inventory',
        ),
        migrations.AddField(
            model_name='beverage',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.vendingmachine'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
