# Generated by Django 4.1 on 2022-09-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0005_remove_vendingmachine_inventory_beverage_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='amount_remaining',
            field=models.IntegerField(null=True),
        ),
    ]
