# Generated by Django 4.1 on 2022-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0007_remove_beverage_amount_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
