# Generated by Django 4.1 on 2022-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0008_vendingmachine_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendingmachine',
            name='coin_count',
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='coin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
