# Generated by Django 4.1 on 2022-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0011_alter_vendingmachine_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='coin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
