# Generated by Django 4.1 on 2022-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0012_alter_vendingmachine_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='coin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
