# Generated by Django 4.1 on 2022-09-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0013_alter_vendingmachine_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='items_remaining',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='type',
        ),
        migrations.AlterField(
            model_name='beverage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beverage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendomatic.beverage')),
                ('machine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendomatic.vendingmachine')),
            ],
        ),
        migrations.AddField(
            model_name='beverage',
            name='type_of_beverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.inventory'),
        ),
    ]
