# Generated by Django 4.1 on 2022-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0015_rename_type_of_beverage_beverage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(default='Soda', max_length=100),
        ),
    ]
