# Generated by Django 4.1 on 2022-09-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0016_alter_beverage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='beverage_name',
            new_name='beverage_id',
        ),
    ]
