# Generated by Django 4.1 on 2022-09-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0018_rename_beverage_id_inventory_beverage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='inventory_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.inventory'),
        ),
    ]
