# Generated by Django 4.1 on 2022-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0020_rename_inventory_name_beverage_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
