# Generated by Django 4.1 on 2022-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0021_alter_beverage_id_alter_beverage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.IntegerField(null=True),
        ),
    ]
