# Generated by Django 4.1 on 2022-09-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0022_alter_beverage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='inventory_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vendomatic.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='beverage_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.beverage'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='machine_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.vendingmachine'),
            preserve_default=False,
        ),
    ]
