# Generated by Django 4.1 on 2022-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0024_alter_beverage_id_alter_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverage',
            name='inventory_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='beverage_name',
        ),
    ]
