# Generated by Django 4.1 on 2022-09-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0025_remove_beverage_inventory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='inventory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.inventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='beverage_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.beverage'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='machine_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.vendingmachine'),
        ),
    ]
