# Generated by Django 4.1 on 2022-09-05 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0027_alter_beverage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeverageInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='beverage',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendomatic.inventory'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(blank=True, choices=[('SODA', 'SODA'), ('water', 'WATER'), ('juice', 'JUICE')], max_length=5, null=True),
        ),
    ]
