# Generated by Django 4.1 on 2022-09-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0029_alter_beverage_id_alter_beverage_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeverageInventory',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='beverage_name',
            new_name='beverage_id',
        ),
    ]
