# Generated by Django 4.1 on 2022-09-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0030_delete_beverageinventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='beverage_id',
            new_name='beverage_name',
        ),
    ]
