# Generated by Django 4.1 on 2022-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0031_rename_beverage_id_inventory_beverage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='beverage_name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='juice_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='soda_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='inventory',
            name='water_count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
