# Generated by Django 4.1 on 2022-09-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0032_remove_inventory_beverage_name_inventory_juice_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beverage',
            old_name='inventory_id',
            new_name='inventory_name',
        ),
    ]
