# Generated by Django 4.1 on 2022-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0034_vendingmachine_total_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendingmachine',
            name='coin',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
