# Generated by Django 4.1 on 2022-09-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendomatic', '0035_alter_vendingmachine_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='vended_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='total_coin',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
